// Code generated by MockGen. DO NOT EDIT.
// Source: embedding_job.go
//
// Generated by this command:
//
//	mockgen -source=embedding_job.go -destination=mock_repository/mock_embedding_job.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	repository "embedding-server/api/repository"
	json "encoding/json"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockJobRepository is a mock of JobRepository interface.
type MockJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepositoryMockRecorder
	isgomock struct{}
}

// MockJobRepositoryMockRecorder is the mock recorder for MockJobRepository.
type MockJobRepositoryMockRecorder struct {
	mock *MockJobRepository
}

// NewMockJobRepository creates a new mock instance.
func NewMockJobRepository(ctrl *gomock.Controller) *MockJobRepository {
	mock := &MockJobRepository{ctrl: ctrl}
	mock.recorder = &MockJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepository) EXPECT() *MockJobRepositoryMockRecorder {
	return m.recorder
}

// ClaimJob mocks base method.
func (m *MockJobRepository) ClaimJob(ctx context.Context) (uuid.UUID, json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimJob", ctx)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(json.RawMessage)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimJob indicates an expected call of ClaimJob.
func (mr *MockJobRepositoryMockRecorder) ClaimJob(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimJob", reflect.TypeOf((*MockJobRepository)(nil).ClaimJob), ctx)
}

// CleanupExpiredJobs mocks base method.
func (m *MockJobRepository) CleanupExpiredJobs(ctx context.Context, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredJobs", ctx, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredJobs indicates an expected call of CleanupExpiredJobs.
func (mr *MockJobRepositoryMockRecorder) CleanupExpiredJobs(ctx, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredJobs", reflect.TypeOf((*MockJobRepository)(nil).CleanupExpiredJobs), ctx, ttl)
}

// CompleteJob mocks base method.
func (m *MockJobRepository) CompleteJob(ctx context.Context, id uuid.UUID, result json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteJob", ctx, id, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteJob indicates an expected call of CompleteJob.
func (mr *MockJobRepositoryMockRecorder) CompleteJob(ctx, id, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteJob", reflect.TypeOf((*MockJobRepository)(nil).CompleteJob), ctx, id, result)
}

// CountPendingJobs mocks base method.
func (m *MockJobRepository) CountPendingJobs(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingJobs", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingJobs indicates an expected call of CountPendingJobs.
func (mr *MockJobRepositoryMockRecorder) CountPendingJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingJobs", reflect.TypeOf((*MockJobRepository)(nil).CountPendingJobs), ctx)
}

// CreateJob mocks base method.
func (m *MockJobRepository) CreateJob(ctx context.Context, id uuid.UUID, payload json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, id, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobRepositoryMockRecorder) CreateJob(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobRepository)(nil).CreateJob), ctx, id, payload)
}

// FailJob mocks base method.
func (m *MockJobRepository) FailJob(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailJob", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailJob indicates an expected call of FailJob.
func (mr *MockJobRepositoryMockRecorder) FailJob(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailJob", reflect.TypeOf((*MockJobRepository)(nil).FailJob), ctx, id)
}

// GetJobPayload mocks base method.
func (m *MockJobRepository) GetJobPayload(ctx context.Context, id uuid.UUID) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobPayload", ctx, id)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobPayload indicates an expected call of GetJobPayload.
func (mr *MockJobRepositoryMockRecorder) GetJobPayload(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobPayload", reflect.TypeOf((*MockJobRepository)(nil).GetJobPayload), ctx, id)
}

// GetJobState mocks base method.
func (m *MockJobRepository) GetJobState(ctx context.Context, id uuid.UUID) (repository.JobState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobState", ctx, id)
	ret0, _ := ret[0].(repository.JobState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobState indicates an expected call of GetJobState.
func (mr *MockJobRepositoryMockRecorder) GetJobState(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobState", reflect.TypeOf((*MockJobRepository)(nil).GetJobState), ctx, id)
}
