// Code generated by MockGen. DO NOT EDIT.
// Source: embedding_cache.go
//
// Generated by this command:
//
//	mockgen -source=embedding_cache.go -destination=mock_repository/mock_embedding_cache.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheRepository is a mock of CacheRepository interface.
type MockCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockCacheRepositoryMockRecorder is the mock recorder for MockCacheRepository.
type MockCacheRepositoryMockRecorder struct {
	mock *MockCacheRepository
}

// NewMockCacheRepository creates a new mock instance.
func NewMockCacheRepository(ctrl *gomock.Controller) *MockCacheRepository {
	mock := &MockCacheRepository{ctrl: ctrl}
	mock.recorder = &MockCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepository) EXPECT() *MockCacheRepositoryMockRecorder {
	return m.recorder
}

// GetTextCache mocks base method.
func (m *MockCacheRepository) GetTextCache(ctx context.Context, text string) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextCache", ctx, text)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTextCache indicates an expected call of GetTextCache.
func (mr *MockCacheRepositoryMockRecorder) GetTextCache(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextCache", reflect.TypeOf((*MockCacheRepository)(nil).GetTextCache), ctx, text)
}

// PruneCache mocks base method.
func (m *MockCacheRepository) PruneCache(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneCache", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneCache indicates an expected call of PruneCache.
func (mr *MockCacheRepositoryMockRecorder) PruneCache(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneCache", reflect.TypeOf((*MockCacheRepository)(nil).PruneCache), ctx)
}

// SetTextCache mocks base method.
func (m *MockCacheRepository) SetTextCache(ctx context.Context, text string, value json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTextCache", ctx, text, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTextCache indicates an expected call of SetTextCache.
func (mr *MockCacheRepositoryMockRecorder) SetTextCache(ctx, text, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTextCache", reflect.TypeOf((*MockCacheRepository)(nil).SetTextCache), ctx, text, value)
}
