// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EmbeddingJobStatusStatus.
const (
	Completed  EmbeddingJobStatusStatus = "completed"
	Failed     EmbeddingJobStatusStatus = "failed"
	Pending    EmbeddingJobStatusStatus = "pending"
	Processing EmbeddingJobStatusStatus = "processing"
)

// Valid indicates whether the value is a known member of the EmbeddingJobStatusStatus enum.
func (e EmbeddingJobStatusStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Processing:
		return true
	default:
		return false
	}
}

// Defines values for WorkerJobKind.
const (
	Image WorkerJobKind = "image"
	Text  WorkerJobKind = "text"
)

// Valid indicates whether the value is a known member of the WorkerJobKind enum.
func (e WorkerJobKind) Valid() bool {
	switch e {
	case Image:
		return true
	case Text:
		return true
	default:
		return false
	}
}

// ClaimWorkerJobRequest defines model for ClaimWorkerJobRequest.
type ClaimWorkerJobRequest struct {
	// Kinds 取得したいジョブ種別。省略時は text と image（text を優先して返す）。
	Kinds *[]WorkerJobKind `json:"kinds,omitempty"`
}

// EmbeddingImageFile 埋め込みに用いる画像バイナリ。
// 対応形式: image/png, image/jpeg, image/webp。
// 1ファイルあたり最大 20 MiB（20971520 bytes）。
type EmbeddingImageFile = openapi_types.File

// EmbeddingImageObject worker が参照する画像オブジェクト
type EmbeddingImageObject struct {
	// Key worker がオブジェクトストレージから取得する画像オブジェクトキー
	Key string `json:"key"`
}

// EmbeddingImageObjects worker が参照する画像オブジェクトのリスト
type EmbeddingImageObjects = []EmbeddingImageObject

// EmbeddingJobAccepted defines model for EmbeddingJobAccepted.
type EmbeddingJobAccepted struct {
	Id JobId `json:"id"`
}

// EmbeddingJobStatus defines model for EmbeddingJobStatus.
type EmbeddingJobStatus struct {
	Id     JobId                    `json:"id"`
	Result *EmbeddingResult         `json:"result,omitempty"`
	Status EmbeddingJobStatusStatus `json:"status"`
}

// EmbeddingJobStatusStatus defines model for EmbeddingJobStatus.Status.
type EmbeddingJobStatusStatus string

// EmbeddingResult defines model for EmbeddingResult.
type EmbeddingResult struct {
	// Vector 正規化済みの埋め込みベクトル。
	// Qwen3-VL-Embedding-8B の出力次元は 4096。
	Vector []float32 `json:"vector"`
}

// EmbeddingText 埋め込みに用いるテキスト。
// 1〜8192 文字。空文字は不可。
type EmbeddingText = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message エラーメッセージ
	Message string `json:"message"`
}

// JobId defines model for JobId.
type JobId = openapi_types.UUID

// WebhookUrl ジョブ完了・失敗時に POST する URL（任意）
type WebhookUrl = string

// WorkerJobKind text は画像なしジョブ、image は画像付きジョブ（multimodal 含む）
type WorkerJobKind string

// WorkerJobPayload worker が処理するジョブ内容
type WorkerJobPayload struct {
	// ImageObjects worker が参照する画像オブジェクトのリスト
	ImageObjects *EmbeddingImageObjects `json:"image_objects,omitempty"`

	// Text 埋め込みに用いるテキスト。
	// 1〜8192 文字。空文字は不可。
	Text *EmbeddingText `json:"text,omitempty"`
}

// CompleteWorkerJobJSONBody defines parameters for CompleteWorkerJob.
type CompleteWorkerJobJSONBody struct {
	Result EmbeddingResult `json:"result"`
}

// PostEmbeddingsImagesMultipartBody defines parameters for PostEmbeddingsImages.
type PostEmbeddingsImagesMultipartBody struct {
	Images []EmbeddingImageFile `json:"images"`

	// WebhookUrl ジョブ完了・失敗時に POST する URL（任意）
	WebhookUrl *WebhookUrl `json:"webhook_url,omitempty"`
}

// PostEmbeddingsMultimodalMultipartBody defines parameters for PostEmbeddingsMultimodal.
type PostEmbeddingsMultimodalMultipartBody struct {
	Images *[]EmbeddingImageFile `json:"images,omitempty"`

	// Text 埋め込みに用いるテキスト。
	// 1〜8192 文字。空文字は不可。
	Text *EmbeddingText `json:"text,omitempty"`

	// WebhookUrl ジョブ完了・失敗時に POST する URL（任意）
	WebhookUrl *WebhookUrl `json:"webhook_url,omitempty"`
	union      json.RawMessage
}

// PostEmbeddingsMultimodalMultipartBody0 defines parameters for PostEmbeddingsMultimodal.
type PostEmbeddingsMultimodalMultipartBody0 = interface{}

// PostEmbeddingsMultimodalMultipartBody1 defines parameters for PostEmbeddingsMultimodal.
type PostEmbeddingsMultimodalMultipartBody1 = interface{}

// PostEmbeddingsTextJSONBody defines parameters for PostEmbeddingsText.
type PostEmbeddingsTextJSONBody struct {
	// Text 埋め込みに用いるテキスト。
	// 1〜8192 文字。空文字は不可。
	Text EmbeddingText `json:"text"`
}

// ClaimWorkerJobJSONRequestBody defines body for ClaimWorkerJob for application/json ContentType.
type ClaimWorkerJobJSONRequestBody = ClaimWorkerJobRequest

// CompleteWorkerJobJSONRequestBody defines body for CompleteWorkerJob for application/json ContentType.
type CompleteWorkerJobJSONRequestBody CompleteWorkerJobJSONBody

// PostEmbeddingsImagesMultipartRequestBody defines body for PostEmbeddingsImages for multipart/form-data ContentType.
type PostEmbeddingsImagesMultipartRequestBody PostEmbeddingsImagesMultipartBody

// PostEmbeddingsMultimodalMultipartRequestBody defines body for PostEmbeddingsMultimodal for multipart/form-data ContentType.
type PostEmbeddingsMultimodalMultipartRequestBody PostEmbeddingsMultimodalMultipartBody

// PostEmbeddingsTextJSONRequestBody defines body for PostEmbeddingsText for application/json ContentType.
type PostEmbeddingsTextJSONRequestBody PostEmbeddingsTextJSONBody

// AsPostEmbeddingsMultimodalMultipartBody0 returns the union data inside the PostEmbeddingsMultimodalMultipartBody as a PostEmbeddingsMultimodalMultipartBody0
func (t PostEmbeddingsMultimodalMultipartBody) AsPostEmbeddingsMultimodalMultipartBody0() (PostEmbeddingsMultimodalMultipartBody0, error) {
	var body PostEmbeddingsMultimodalMultipartBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostEmbeddingsMultimodalMultipartBody0 overwrites any union data inside the PostEmbeddingsMultimodalMultipartBody as the provided PostEmbeddingsMultimodalMultipartBody0
func (t *PostEmbeddingsMultimodalMultipartBody) FromPostEmbeddingsMultimodalMultipartBody0(v PostEmbeddingsMultimodalMultipartBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostEmbeddingsMultimodalMultipartBody0 performs a merge with any union data inside the PostEmbeddingsMultimodalMultipartBody, using the provided PostEmbeddingsMultimodalMultipartBody0
func (t *PostEmbeddingsMultimodalMultipartBody) MergePostEmbeddingsMultimodalMultipartBody0(v PostEmbeddingsMultimodalMultipartBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPostEmbeddingsMultimodalMultipartBody1 returns the union data inside the PostEmbeddingsMultimodalMultipartBody as a PostEmbeddingsMultimodalMultipartBody1
func (t PostEmbeddingsMultimodalMultipartBody) AsPostEmbeddingsMultimodalMultipartBody1() (PostEmbeddingsMultimodalMultipartBody1, error) {
	var body PostEmbeddingsMultimodalMultipartBody1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPostEmbeddingsMultimodalMultipartBody1 overwrites any union data inside the PostEmbeddingsMultimodalMultipartBody as the provided PostEmbeddingsMultimodalMultipartBody1
func (t *PostEmbeddingsMultimodalMultipartBody) FromPostEmbeddingsMultimodalMultipartBody1(v PostEmbeddingsMultimodalMultipartBody1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePostEmbeddingsMultimodalMultipartBody1 performs a merge with any union data inside the PostEmbeddingsMultimodalMultipartBody, using the provided PostEmbeddingsMultimodalMultipartBody1
func (t *PostEmbeddingsMultimodalMultipartBody) MergePostEmbeddingsMultimodalMultipartBody1(v PostEmbeddingsMultimodalMultipartBody1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PostEmbeddingsMultimodalMultipartBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Images != nil {
		object["images"], err = json.Marshal(t.Images)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'images': %w", err)
		}
	}

	if t.Text != nil {
		object["text"], err = json.Marshal(t.Text)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'text': %w", err)
		}
	}

	if t.WebhookUrl != nil {
		object["webhook_url"], err = json.Marshal(t.WebhookUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'webhook_url': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *PostEmbeddingsMultimodalMultipartBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["images"]; found {
		err = json.Unmarshal(raw, &t.Images)
		if err != nil {
			return fmt.Errorf("error reading 'images': %w", err)
		}
	}

	if raw, found := object["text"]; found {
		err = json.Unmarshal(raw, &t.Text)
		if err != nil {
			return fmt.Errorf("error reading 'text': %w", err)
		}
	}

	if raw, found := object["webhook_url"]; found {
		err = json.Unmarshal(raw, &t.WebhookUrl)
		if err != nil {
			return fmt.Errorf("error reading 'webhook_url': %w", err)
		}
	}

	return err
}
