// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 次の pending ジョブをロックして取得
	// (POST /internal/worker/jobs/claim)
	PostInternalWorkerJobsClaim(ctx echo.Context) error
	// ジョブを完了にする
	// (POST /internal/worker/jobs/{id}/complete)
	PostInternalWorkerJobsIdComplete(ctx echo.Context, id JobId) error
	// ジョブを失敗にする
	// (POST /internal/worker/jobs/{id}/fail)
	PostInternalWorkerJobsIdFail(ctx echo.Context, id JobId) error
	// 画像の埋め込みベクトルを返す
	// (POST /v1/embeddings/image)
	PostEmbeddingsImage(ctx echo.Context) error
	// テキストの埋め込みベクトルを返す
	// (POST /v1/embeddings/text)
	PostEmbeddingsText(ctx echo.Context) error
	// テキストと画像を合わせた埋め込みベクトルを返す
	// (POST /v1/embeddings/text-image)
	PostEmbeddingsTextImage(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostInternalWorkerJobsClaim converts echo context to params.
func (w *ServerInterfaceWrapper) PostInternalWorkerJobsClaim(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInternalWorkerJobsClaim(ctx)
	return err
}

// PostInternalWorkerJobsIdComplete converts echo context to params.
func (w *ServerInterfaceWrapper) PostInternalWorkerJobsIdComplete(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInternalWorkerJobsIdComplete(ctx, id)
	return err
}

// PostInternalWorkerJobsIdFail converts echo context to params.
func (w *ServerInterfaceWrapper) PostInternalWorkerJobsIdFail(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInternalWorkerJobsIdFail(ctx, id)
	return err
}

// PostEmbeddingsImage converts echo context to params.
func (w *ServerInterfaceWrapper) PostEmbeddingsImage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEmbeddingsImage(ctx)
	return err
}

// PostEmbeddingsText converts echo context to params.
func (w *ServerInterfaceWrapper) PostEmbeddingsText(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEmbeddingsText(ctx)
	return err
}

// PostEmbeddingsTextImage converts echo context to params.
func (w *ServerInterfaceWrapper) PostEmbeddingsTextImage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEmbeddingsTextImage(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/internal/worker/jobs/claim", wrapper.PostInternalWorkerJobsClaim, options.OperationMiddlewares["postInternalWorkerJobsClaim"]...)
	router.POST(options.BaseURL+"/internal/worker/jobs/:id/complete", wrapper.PostInternalWorkerJobsIdComplete, options.OperationMiddlewares["postInternalWorkerJobsIdComplete"]...)
	router.POST(options.BaseURL+"/internal/worker/jobs/:id/fail", wrapper.PostInternalWorkerJobsIdFail, options.OperationMiddlewares["postInternalWorkerJobsIdFail"]...)
	router.POST(options.BaseURL+"/v1/embeddings/image", wrapper.PostEmbeddingsImage, options.OperationMiddlewares["postEmbeddingsImage"]...)
	router.POST(options.BaseURL+"/v1/embeddings/text", wrapper.PostEmbeddingsText, options.OperationMiddlewares["postEmbeddingsText"]...)
	router.POST(options.BaseURL+"/v1/embeddings/text-image", wrapper.PostEmbeddingsTextImage, options.OperationMiddlewares["postEmbeddingsTextImage"]...)

}

type NoContentResponse struct {
}

type PostInternalWorkerJobsClaimRequestObject struct {
}

type PostInternalWorkerJobsClaimResponseObject interface {
	VisitPostInternalWorkerJobsClaimResponse(w http.ResponseWriter) error
}

type PostInternalWorkerJobsClaim200JSONResponse struct {
	Id int64 `json:"id"`

	// Payload worker が処理するジョブ内容
	Payload WorkerJobPayload `json:"payload"`
}

func (response PostInternalWorkerJobsClaim200JSONResponse) VisitPostInternalWorkerJobsClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostInternalWorkerJobsClaim204Response = NoContentResponse

func (response PostInternalWorkerJobsClaim204Response) VisitPostInternalWorkerJobsClaimResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PostInternalWorkerJobsClaim500JSONResponse ErrorResponse

func (response PostInternalWorkerJobsClaim500JSONResponse) VisitPostInternalWorkerJobsClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostInternalWorkerJobsIdCompleteRequestObject struct {
	Id   JobId `json:"id"`
	Body *PostInternalWorkerJobsIdCompleteJSONRequestBody
}

type PostInternalWorkerJobsIdCompleteResponseObject interface {
	VisitPostInternalWorkerJobsIdCompleteResponse(w http.ResponseWriter) error
}

type PostInternalWorkerJobsIdComplete204Response = NoContentResponse

func (response PostInternalWorkerJobsIdComplete204Response) VisitPostInternalWorkerJobsIdCompleteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PostInternalWorkerJobsIdComplete400JSONResponse ErrorResponse

func (response PostInternalWorkerJobsIdComplete400JSONResponse) VisitPostInternalWorkerJobsIdCompleteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostInternalWorkerJobsIdComplete404JSONResponse ErrorResponse

func (response PostInternalWorkerJobsIdComplete404JSONResponse) VisitPostInternalWorkerJobsIdCompleteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostInternalWorkerJobsIdComplete500JSONResponse ErrorResponse

func (response PostInternalWorkerJobsIdComplete500JSONResponse) VisitPostInternalWorkerJobsIdCompleteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostInternalWorkerJobsIdFailRequestObject struct {
	Id JobId `json:"id"`
}

type PostInternalWorkerJobsIdFailResponseObject interface {
	VisitPostInternalWorkerJobsIdFailResponse(w http.ResponseWriter) error
}

type PostInternalWorkerJobsIdFail204Response = NoContentResponse

func (response PostInternalWorkerJobsIdFail204Response) VisitPostInternalWorkerJobsIdFailResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PostInternalWorkerJobsIdFail400JSONResponse ErrorResponse

func (response PostInternalWorkerJobsIdFail400JSONResponse) VisitPostInternalWorkerJobsIdFailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostInternalWorkerJobsIdFail404JSONResponse ErrorResponse

func (response PostInternalWorkerJobsIdFail404JSONResponse) VisitPostInternalWorkerJobsIdFailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostInternalWorkerJobsIdFail500JSONResponse ErrorResponse

func (response PostInternalWorkerJobsIdFail500JSONResponse) VisitPostInternalWorkerJobsIdFailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImageRequestObject struct {
	Body *multipart.Reader
}

type PostEmbeddingsImageResponseObject interface {
	VisitPostEmbeddingsImageResponse(w http.ResponseWriter) error
}

type PostEmbeddingsImage200JSONResponse EmbeddingResult

func (response PostEmbeddingsImage200JSONResponse) VisitPostEmbeddingsImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImage400JSONResponse ErrorResponse

func (response PostEmbeddingsImage400JSONResponse) VisitPostEmbeddingsImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImage413JSONResponse ErrorResponse

func (response PostEmbeddingsImage413JSONResponse) VisitPostEmbeddingsImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImage500JSONResponse ErrorResponse

func (response PostEmbeddingsImage500JSONResponse) VisitPostEmbeddingsImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImage503ResponseHeaders struct {
	RetryAfter *int
}

type PostEmbeddingsImage503JSONResponse struct {
	Body    ErrorResponse
	Headers PostEmbeddingsImage503ResponseHeaders
}

func (response PostEmbeddingsImage503JSONResponse) VisitPostEmbeddingsImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImage504JSONResponse ErrorResponse

func (response PostEmbeddingsImage504JSONResponse) VisitPostEmbeddingsImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(504)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsTextRequestObject struct {
	Body *PostEmbeddingsTextJSONRequestBody
}

type PostEmbeddingsTextResponseObject interface {
	VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error
}

type PostEmbeddingsText200JSONResponse EmbeddingResult

func (response PostEmbeddingsText200JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText400JSONResponse ErrorResponse

func (response PostEmbeddingsText400JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText500JSONResponse ErrorResponse

func (response PostEmbeddingsText500JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText503ResponseHeaders struct {
	RetryAfter *int
}

type PostEmbeddingsText503JSONResponse struct {
	Body    ErrorResponse
	Headers PostEmbeddingsText503ResponseHeaders
}

func (response PostEmbeddingsText503JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText504JSONResponse ErrorResponse

func (response PostEmbeddingsText504JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(504)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsTextImageRequestObject struct {
	Body *multipart.Reader
}

type PostEmbeddingsTextImageResponseObject interface {
	VisitPostEmbeddingsTextImageResponse(w http.ResponseWriter) error
}

type PostEmbeddingsTextImage200JSONResponse EmbeddingResult

func (response PostEmbeddingsTextImage200JSONResponse) VisitPostEmbeddingsTextImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsTextImage400JSONResponse ErrorResponse

func (response PostEmbeddingsTextImage400JSONResponse) VisitPostEmbeddingsTextImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsTextImage413JSONResponse ErrorResponse

func (response PostEmbeddingsTextImage413JSONResponse) VisitPostEmbeddingsTextImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsTextImage500JSONResponse ErrorResponse

func (response PostEmbeddingsTextImage500JSONResponse) VisitPostEmbeddingsTextImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsTextImage503ResponseHeaders struct {
	RetryAfter *int
}

type PostEmbeddingsTextImage503JSONResponse struct {
	Body    ErrorResponse
	Headers PostEmbeddingsTextImage503ResponseHeaders
}

func (response PostEmbeddingsTextImage503JSONResponse) VisitPostEmbeddingsTextImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsTextImage504JSONResponse ErrorResponse

func (response PostEmbeddingsTextImage504JSONResponse) VisitPostEmbeddingsTextImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(504)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// 次の pending ジョブをロックして取得
	// (POST /internal/worker/jobs/claim)
	PostInternalWorkerJobsClaim(ctx context.Context, request PostInternalWorkerJobsClaimRequestObject) (PostInternalWorkerJobsClaimResponseObject, error)
	// ジョブを完了にする
	// (POST /internal/worker/jobs/{id}/complete)
	PostInternalWorkerJobsIdComplete(ctx context.Context, request PostInternalWorkerJobsIdCompleteRequestObject) (PostInternalWorkerJobsIdCompleteResponseObject, error)
	// ジョブを失敗にする
	// (POST /internal/worker/jobs/{id}/fail)
	PostInternalWorkerJobsIdFail(ctx context.Context, request PostInternalWorkerJobsIdFailRequestObject) (PostInternalWorkerJobsIdFailResponseObject, error)
	// 画像の埋め込みベクトルを返す
	// (POST /v1/embeddings/image)
	PostEmbeddingsImage(ctx context.Context, request PostEmbeddingsImageRequestObject) (PostEmbeddingsImageResponseObject, error)
	// テキストの埋め込みベクトルを返す
	// (POST /v1/embeddings/text)
	PostEmbeddingsText(ctx context.Context, request PostEmbeddingsTextRequestObject) (PostEmbeddingsTextResponseObject, error)
	// テキストと画像を合わせた埋め込みベクトルを返す
	// (POST /v1/embeddings/text-image)
	PostEmbeddingsTextImage(ctx context.Context, request PostEmbeddingsTextImageRequestObject) (PostEmbeddingsTextImageResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostInternalWorkerJobsClaim operation middleware
func (sh *strictHandler) PostInternalWorkerJobsClaim(ctx echo.Context) error {
	var request PostInternalWorkerJobsClaimRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostInternalWorkerJobsClaim(ctx.Request().Context(), request.(PostInternalWorkerJobsClaimRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostInternalWorkerJobsClaim")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostInternalWorkerJobsClaimResponseObject); ok {
		return validResponse.VisitPostInternalWorkerJobsClaimResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostInternalWorkerJobsIdComplete operation middleware
func (sh *strictHandler) PostInternalWorkerJobsIdComplete(ctx echo.Context, id JobId) error {
	var request PostInternalWorkerJobsIdCompleteRequestObject

	request.Id = id

	var body PostInternalWorkerJobsIdCompleteJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostInternalWorkerJobsIdComplete(ctx.Request().Context(), request.(PostInternalWorkerJobsIdCompleteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostInternalWorkerJobsIdComplete")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostInternalWorkerJobsIdCompleteResponseObject); ok {
		return validResponse.VisitPostInternalWorkerJobsIdCompleteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostInternalWorkerJobsIdFail operation middleware
func (sh *strictHandler) PostInternalWorkerJobsIdFail(ctx echo.Context, id JobId) error {
	var request PostInternalWorkerJobsIdFailRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostInternalWorkerJobsIdFail(ctx.Request().Context(), request.(PostInternalWorkerJobsIdFailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostInternalWorkerJobsIdFail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostInternalWorkerJobsIdFailResponseObject); ok {
		return validResponse.VisitPostInternalWorkerJobsIdFailResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostEmbeddingsImage operation middleware
func (sh *strictHandler) PostEmbeddingsImage(ctx echo.Context) error {
	var request PostEmbeddingsImageRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostEmbeddingsImage(ctx.Request().Context(), request.(PostEmbeddingsImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEmbeddingsImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostEmbeddingsImageResponseObject); ok {
		return validResponse.VisitPostEmbeddingsImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostEmbeddingsText operation middleware
func (sh *strictHandler) PostEmbeddingsText(ctx echo.Context) error {
	var request PostEmbeddingsTextRequestObject

	var body PostEmbeddingsTextJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostEmbeddingsText(ctx.Request().Context(), request.(PostEmbeddingsTextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEmbeddingsText")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostEmbeddingsTextResponseObject); ok {
		return validResponse.VisitPostEmbeddingsTextResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostEmbeddingsTextImage operation middleware
func (sh *strictHandler) PostEmbeddingsTextImage(ctx echo.Context) error {
	var request PostEmbeddingsTextImageRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostEmbeddingsTextImage(ctx.Request().Context(), request.(PostEmbeddingsTextImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEmbeddingsTextImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostEmbeddingsTextImageResponseObject); ok {
		return validResponse.VisitPostEmbeddingsTextImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
