// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 次の pending ジョブをロックして取得
	// (POST /internal/worker/jobs/claim)
	ClaimWorkerJob(ctx *echo.Context) error
	// ジョブを完了にする
	// (POST /internal/worker/jobs/{id}/complete)
	CompleteWorkerJob(ctx *echo.Context, id JobId) error
	// ジョブを失敗にする
	// (POST /internal/worker/jobs/{id}/fail)
	FailWorkerJob(ctx *echo.Context, id JobId) error
	// 画像群の埋め込みベクトルを返す
	// (POST /v1/embeddings/images)
	PostEmbeddingsImages(ctx *echo.Context) error
	// テキストと画像群を合わせた埋め込みベクトルを返す
	// (POST /v1/embeddings/multimodal)
	PostEmbeddingsMultimodal(ctx *echo.Context) error
	// テキストの埋め込みベクトルを返す
	// (POST /v1/embeddings/text)
	PostEmbeddingsText(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ClaimWorkerJob converts echo context to params.
func (w *ServerInterfaceWrapper) ClaimWorkerJob(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ClaimWorkerJob(ctx)
	return err
}

// CompleteWorkerJob converts echo context to params.
func (w *ServerInterfaceWrapper) CompleteWorkerJob(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CompleteWorkerJob(ctx, id)
	return err
}

// FailWorkerJob converts echo context to params.
func (w *ServerInterfaceWrapper) FailWorkerJob(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FailWorkerJob(ctx, id)
	return err
}

// PostEmbeddingsImages converts echo context to params.
func (w *ServerInterfaceWrapper) PostEmbeddingsImages(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEmbeddingsImages(ctx)
	return err
}

// PostEmbeddingsMultimodal converts echo context to params.
func (w *ServerInterfaceWrapper) PostEmbeddingsMultimodal(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEmbeddingsMultimodal(ctx)
	return err
}

// PostEmbeddingsText converts echo context to params.
func (w *ServerInterfaceWrapper) PostEmbeddingsText(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEmbeddingsText(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/internal/worker/jobs/claim", wrapper.ClaimWorkerJob, options.OperationMiddlewares["claimWorkerJob"]...)
	router.POST(options.BaseURL+"/internal/worker/jobs/:id/complete", wrapper.CompleteWorkerJob, options.OperationMiddlewares["completeWorkerJob"]...)
	router.POST(options.BaseURL+"/internal/worker/jobs/:id/fail", wrapper.FailWorkerJob, options.OperationMiddlewares["failWorkerJob"]...)
	router.POST(options.BaseURL+"/v1/embeddings/images", wrapper.PostEmbeddingsImages, options.OperationMiddlewares["postEmbeddingsImages"]...)
	router.POST(options.BaseURL+"/v1/embeddings/multimodal", wrapper.PostEmbeddingsMultimodal, options.OperationMiddlewares["postEmbeddingsMultimodal"]...)
	router.POST(options.BaseURL+"/v1/embeddings/text", wrapper.PostEmbeddingsText, options.OperationMiddlewares["postEmbeddingsText"]...)

}

type NoContentResponse struct {
}

type ClaimWorkerJobRequestObject struct {
}

type ClaimWorkerJobResponseObject interface {
	VisitClaimWorkerJobResponse(w http.ResponseWriter) error
}

type ClaimWorkerJob200JSONResponse struct {
	Id JobId `json:"id"`

	// Payload worker が処理するジョブ内容
	Payload WorkerJobPayload `json:"payload"`
}

func (response ClaimWorkerJob200JSONResponse) VisitClaimWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimWorkerJob204Response = NoContentResponse

func (response ClaimWorkerJob204Response) VisitClaimWorkerJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ClaimWorkerJob500JSONResponse ErrorResponse

func (response ClaimWorkerJob500JSONResponse) VisitClaimWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteWorkerJobRequestObject struct {
	Id   JobId `json:"id"`
	Body *CompleteWorkerJobJSONRequestBody
}

type CompleteWorkerJobResponseObject interface {
	VisitCompleteWorkerJobResponse(w http.ResponseWriter) error
}

type CompleteWorkerJob204Response = NoContentResponse

func (response CompleteWorkerJob204Response) VisitCompleteWorkerJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CompleteWorkerJob400JSONResponse ErrorResponse

func (response CompleteWorkerJob400JSONResponse) VisitCompleteWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteWorkerJob404JSONResponse ErrorResponse

func (response CompleteWorkerJob404JSONResponse) VisitCompleteWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteWorkerJob500JSONResponse ErrorResponse

func (response CompleteWorkerJob500JSONResponse) VisitCompleteWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type FailWorkerJobRequestObject struct {
	Id JobId `json:"id"`
}

type FailWorkerJobResponseObject interface {
	VisitFailWorkerJobResponse(w http.ResponseWriter) error
}

type FailWorkerJob204Response = NoContentResponse

func (response FailWorkerJob204Response) VisitFailWorkerJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type FailWorkerJob400JSONResponse ErrorResponse

func (response FailWorkerJob400JSONResponse) VisitFailWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type FailWorkerJob404JSONResponse ErrorResponse

func (response FailWorkerJob404JSONResponse) VisitFailWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type FailWorkerJob500JSONResponse ErrorResponse

func (response FailWorkerJob500JSONResponse) VisitFailWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImagesRequestObject struct {
	Body *multipart.Reader
}

type PostEmbeddingsImagesResponseObject interface {
	VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error
}

type PostEmbeddingsImages200JSONResponse EmbeddingResult

func (response PostEmbeddingsImages200JSONResponse) VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImages400JSONResponse ErrorResponse

func (response PostEmbeddingsImages400JSONResponse) VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImages500JSONResponse ErrorResponse

func (response PostEmbeddingsImages500JSONResponse) VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImages503ResponseHeaders struct {
	RetryAfter int
}

type PostEmbeddingsImages503JSONResponse struct {
	Body    ErrorResponse
	Headers PostEmbeddingsImages503ResponseHeaders
}

func (response PostEmbeddingsImages503JSONResponse) VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImages504JSONResponse ErrorResponse

func (response PostEmbeddingsImages504JSONResponse) VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(504)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsMultimodalRequestObject struct {
	Body *multipart.Reader
}

type PostEmbeddingsMultimodalResponseObject interface {
	VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error
}

type PostEmbeddingsMultimodal200JSONResponse EmbeddingResult

func (response PostEmbeddingsMultimodal200JSONResponse) VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsMultimodal400JSONResponse ErrorResponse

func (response PostEmbeddingsMultimodal400JSONResponse) VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsMultimodal500JSONResponse ErrorResponse

func (response PostEmbeddingsMultimodal500JSONResponse) VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsMultimodal503ResponseHeaders struct {
	RetryAfter int
}

type PostEmbeddingsMultimodal503JSONResponse struct {
	Body    ErrorResponse
	Headers PostEmbeddingsMultimodal503ResponseHeaders
}

func (response PostEmbeddingsMultimodal503JSONResponse) VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsMultimodal504JSONResponse ErrorResponse

func (response PostEmbeddingsMultimodal504JSONResponse) VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(504)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsTextRequestObject struct {
	Body *PostEmbeddingsTextJSONRequestBody
}

type PostEmbeddingsTextResponseObject interface {
	VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error
}

type PostEmbeddingsText200JSONResponse EmbeddingResult

func (response PostEmbeddingsText200JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText400JSONResponse ErrorResponse

func (response PostEmbeddingsText400JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText500JSONResponse ErrorResponse

func (response PostEmbeddingsText500JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText503ResponseHeaders struct {
	RetryAfter int
}

type PostEmbeddingsText503JSONResponse struct {
	Body    ErrorResponse
	Headers PostEmbeddingsText503ResponseHeaders
}

func (response PostEmbeddingsText503JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText504JSONResponse ErrorResponse

func (response PostEmbeddingsText504JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(504)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// 次の pending ジョブをロックして取得
	// (POST /internal/worker/jobs/claim)
	ClaimWorkerJob(ctx context.Context, request ClaimWorkerJobRequestObject) (ClaimWorkerJobResponseObject, error)
	// ジョブを完了にする
	// (POST /internal/worker/jobs/{id}/complete)
	CompleteWorkerJob(ctx context.Context, request CompleteWorkerJobRequestObject) (CompleteWorkerJobResponseObject, error)
	// ジョブを失敗にする
	// (POST /internal/worker/jobs/{id}/fail)
	FailWorkerJob(ctx context.Context, request FailWorkerJobRequestObject) (FailWorkerJobResponseObject, error)
	// 画像群の埋め込みベクトルを返す
	// (POST /v1/embeddings/images)
	PostEmbeddingsImages(ctx context.Context, request PostEmbeddingsImagesRequestObject) (PostEmbeddingsImagesResponseObject, error)
	// テキストと画像群を合わせた埋め込みベクトルを返す
	// (POST /v1/embeddings/multimodal)
	PostEmbeddingsMultimodal(ctx context.Context, request PostEmbeddingsMultimodalRequestObject) (PostEmbeddingsMultimodalResponseObject, error)
	// テキストの埋め込みベクトルを返す
	// (POST /v1/embeddings/text)
	PostEmbeddingsText(ctx context.Context, request PostEmbeddingsTextRequestObject) (PostEmbeddingsTextResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ClaimWorkerJob operation middleware
func (sh *strictHandler) ClaimWorkerJob(ctx *echo.Context) error {
	var request ClaimWorkerJobRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimWorkerJob(ctx.Request().Context(), request.(ClaimWorkerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimWorkerJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ClaimWorkerJobResponseObject); ok {
		return validResponse.VisitClaimWorkerJobResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CompleteWorkerJob operation middleware
func (sh *strictHandler) CompleteWorkerJob(ctx *echo.Context, id JobId) error {
	var request CompleteWorkerJobRequestObject

	request.Id = id

	var body CompleteWorkerJobJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteWorkerJob(ctx.Request().Context(), request.(CompleteWorkerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteWorkerJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CompleteWorkerJobResponseObject); ok {
		return validResponse.VisitCompleteWorkerJobResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// FailWorkerJob operation middleware
func (sh *strictHandler) FailWorkerJob(ctx *echo.Context, id JobId) error {
	var request FailWorkerJobRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FailWorkerJob(ctx.Request().Context(), request.(FailWorkerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FailWorkerJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(FailWorkerJobResponseObject); ok {
		return validResponse.VisitFailWorkerJobResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostEmbeddingsImages operation middleware
func (sh *strictHandler) PostEmbeddingsImages(ctx *echo.Context) error {
	var request PostEmbeddingsImagesRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostEmbeddingsImages(ctx.Request().Context(), request.(PostEmbeddingsImagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEmbeddingsImages")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostEmbeddingsImagesResponseObject); ok {
		return validResponse.VisitPostEmbeddingsImagesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostEmbeddingsMultimodal operation middleware
func (sh *strictHandler) PostEmbeddingsMultimodal(ctx *echo.Context) error {
	var request PostEmbeddingsMultimodalRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostEmbeddingsMultimodal(ctx.Request().Context(), request.(PostEmbeddingsMultimodalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEmbeddingsMultimodal")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostEmbeddingsMultimodalResponseObject); ok {
		return validResponse.VisitPostEmbeddingsMultimodalResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostEmbeddingsText operation middleware
func (sh *strictHandler) PostEmbeddingsText(ctx *echo.Context) error {
	var request PostEmbeddingsTextRequestObject

	var body PostEmbeddingsTextJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostEmbeddingsText(ctx.Request().Context(), request.(PostEmbeddingsTextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEmbeddingsText")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostEmbeddingsTextResponseObject); ok {
		return validResponse.VisitPostEmbeddingsTextResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FpdTxvZGf4ro9Pe1YkNYdWs7za7XYmom0RppV5sUTXYB5isPTOdGbJByJLPOUAMmNpL+AgpG0JgwVkW",
	"O1U2KgkO/JiXsckVf6E6Zz48tscOLFGSStwk42HOmfe87/M874c9jhJaWtdUrFomio8jXTbkNLawIT5d",
	"1wb7k/xCUVEc6bI1giJIldMYxZGSRBFk4H+OKgZOorhljOIIMhMjOC3zFb838BCKo99FG/tHnb+aUWfb",
	"TCbDNzB1TTWxeN0N7UtNtbBq8Q9JbCYMRbcUjb/7hiZ5f+PL3J34c39KD+JkUlGH+9PyMP5aSeH21fba",
	"LFByfFAFcghkp75QAjIBdLa+sG+zArAi0E1gM8B+hiz9u2pXDuzDVfvNU7taiEsK3zeqq8MR9/KOjv3r",
	"7/GgLtb0AFsEui422gFCgawBnamtZu3Nbak3Jn2jXDup5npjn/+x57PemDQ4ZmHzpDot1qIIGtKMtGyh",
	"OBpUVNkYQxGUlu/9GavD1giKe6siyBrTue9Ny1DUYZSJtJz+5uAdnAjx3vea8R02JCB5u0Drk9tAVhqn",
	"pz8DWwK6B3QbaAVYDkWQbmg6NizFict3eKzbnu07AH3F/2W/AKvy+2QW6LRdWLIPlru/GugusCpqO2gm",
	"CLVvhUED/kOac+oO3jDP6w4gZQ4McSQUQYqF0+a7EB4alkwEpRW131nf45svG4Y81mT9bWyOpkQYm+Nw",
	"FycszWg/T21343irYOeXans5gfByE+DZinsQthO034fcUEqTrYbP1dH0IDa4Qc0GtsTANaZrGP6K71mn",
	"ZyOwKR5/BzsOp7KrV3s+75VqS/ft3WXI0vqz1+41qRztzdmFikegAF34EuFq70ZPGHEMQzNuu+rT7uo0",
	"Nk15OERKgJaAPeO4ZuvAGNB9B+PvxKy3Y5jDfJ31YzI6KvS1zey/Cehe1wZvyWMpTU52Bff9rXpxygE3",
	"BzTbBrZkT03a5VdtFBdq9g+twZizotsUgHHjfarFAhyZTJs7+C1FHdJCfM8ec3FlBNhTEYEssJ0gmgSU",
	"yv5Z6+X1enFK+uJWv0BJEF/23MOjNw+A7Tus9z8Gnzmp+gniEdCnQOftwjKQH472HwL5gTtVJIti/mgv",
	"24TdZv7VXxZrj1eBVIC+FFYXgVXtqcm3rARkWyjehkDSf4H9BGQRaN7bmyNAsXhGQ9hz2yUTG3exwU+F",
	"IuguNkzHObHLPZdjPAiajlVZV1AcXbkcu3yFh1q2RkRQo4pqYUOVU1EHJdE72qAZTaRkJS0ooJkhdP3q",
	"mmRPTQLZ5smssAmkLOlY5aZIvqeBzku6oSWwaYr7ZAfIMmSJkpSAlCTdAasEdP74cIEjUsTDX03y9Yl1",
	"IBP2k1/tYg5IReqN9Xke4DCVuS2cIuhLbqzPAtRSQfTGYvy/RKOMkHU9pSTE+ugdkx9oPFCltJAgecrK",
	"hbvUp1+359vo2qoKguXeZgOhXGjVH99pFOgMt6U31tfJDt850UZtlYmgz87opq58bhLSUIvbYO9pqFPL",
	"jabTvOSJo9ov653QBWxXcKTCcUW2nFqC00MeNoUfXWBfcoCNBvjO4XAfV5IZcZAUtnAQ9i1Ac58IYi1Y",
	"HX8b7pbGIx5YBpyIY9O6piXHzgFPwy8LTqWvbhXRijh3l9NgrZFKjku5enlZ+H4tRNuaaR2U2WCqbyC3",
	"7BI9S4Lg4BJJHgAp+7s6hbiXwXbFM+2KuXd0+KO9+9B9zFWN5s4k06YTZ6VM3welDK83K5wmbkLJH+3N",
	"1XY3+OnJimNO34czp5a/b5cfOdEPivbx1iyQTVHdzwA5APJvoA8+YX0JCopdzh+9nhKJisPmHFIyJCup",
	"zjLytayk3o+EXMD3Ar4N+G7+p7a4fHr43u2J+hWkGRXVvtm55Guq6766xuu5ozertVzRqeqcxsJj0AGQ",
	"bftgsvZszcnNbrffoQNtzhVt5d0tzbT8DGb2O3Z2S6Dp0ZSl6LJhRXnvdCkpW3LXEs8/+W/o48VwKSN6",
	"TbeL7+va0rfWes67wzPvu/LVe0RkW4HQhsmO44MPrSR+dCWBszXeGjhulMS8bUNQZwfYdIvInFRztceP",
	"aovPeU9HXwLdBPoa2L4z1OMEKu4AzZ5Upz8twnNbrnxIWwKS0tTcTvM21BNFyFLB7ef8PinYB5NANhpU",
	"n5p7myUe+QtAnvAulkygCBrBctKdJd/GljF26YshC4dNsP5Vsn8q8bzBcfYM6KajKPXt+dri866DZpdL",
	"XPaGscEPKZzY9xGc6A1c8kAPxSD4iRgbbIkcuCy8yXNQi6w7M4b6wWaXuZ2vmgGhb+h5qMYL6qS1pJzq",
	"rPMWvmdJf/AY5U1PSsBecEaxH8UhXjjjOP4s/zM55H09X+F+4hU5bUn5dqFyzN60dPkfN5d80/DHufKJ",
	"rI7dHBK1W1DbxeRrIBMZD1V8XsB9xDz0HgdzF2kqzBDBDbbvZSZS9krOi5x0kZP+H3NS8zi71EhRHKQ5",
	"oAUeg+ZR0DnTladQH7khCZvmn2VwnyWt99k8v2a52goFUrHnXtRW6PHhgj3362myltDi9zVA/G1ZoD3N",
	"XWSGM4xCgkjK1yfW7ZlXHCV+O3P9LzdvSCEjkgv9v9D/T0T/z9GW8F3F95XOuLPZyLdLs/WV1/X55/ZT",
	"hiJo1EihOBqxLD0ejaa0hJwa0UwrfjV2NSZGoO4bxrtRzPtCt+NXue25IAA3L6e4IzX3l06BE/ECv0Vp",
	"vHxgz3J8Cbg5P2aoiB8G7ACr1hdKgd9NtcznMgOZ/wUAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
