// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// EmbeddingImageFile 埋め込みに用いる画像バイナリ
type EmbeddingImageFile = openapi_types.File

// EmbeddingImagePath worker が参照するローカルファイルパス
type EmbeddingImagePath = string

// EmbeddingImagePaths worker が参照するローカルファイルパスのリスト
type EmbeddingImagePaths = []EmbeddingImagePath

// EmbeddingResult defines model for EmbeddingResult.
type EmbeddingResult struct {
	// Vector 正規化済みの埋め込みベクトル
	Vector []float32 `json:"vector"`
}

// EmbeddingText 埋め込みに用いるテキスト
type EmbeddingText = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message エラーメッセージ
	Message string `json:"message"`
}

// JobId defines model for JobId.
type JobId = openapi_types.UUID

// WorkerJobPayload worker が処理するジョブ内容
type WorkerJobPayload struct {
	// ImagePaths worker が参照するローカルファイルパスのリスト
	ImagePaths *EmbeddingImagePaths `json:"image_paths,omitempty"`

	// Text 埋め込みに用いるテキスト
	Text *EmbeddingText `json:"text,omitempty"`
}

// CompleteWorkerJobJSONBody defines parameters for CompleteWorkerJob.
type CompleteWorkerJobJSONBody struct {
	Result EmbeddingResult `json:"result"`
}

// PostEmbeddingsImagesMultipartBody defines parameters for PostEmbeddingsImages.
type PostEmbeddingsImagesMultipartBody struct {
	Images []EmbeddingImageFile `json:"images"`
}

// PostEmbeddingsMultimodalMultipartBody defines parameters for PostEmbeddingsMultimodal.
type PostEmbeddingsMultimodalMultipartBody struct {
	Images *[]EmbeddingImageFile `json:"images,omitempty"`

	// Text 埋め込みに用いるテキスト
	Text *EmbeddingText `json:"text,omitempty"`
}

// PostEmbeddingsTextJSONBody defines parameters for PostEmbeddingsText.
type PostEmbeddingsTextJSONBody struct {
	// Text 埋め込みに用いるテキスト
	Text EmbeddingText `json:"text"`
}

// CompleteWorkerJobJSONRequestBody defines body for CompleteWorkerJob for application/json ContentType.
type CompleteWorkerJobJSONRequestBody CompleteWorkerJobJSONBody

// PostEmbeddingsImagesMultipartRequestBody defines body for PostEmbeddingsImages for multipart/form-data ContentType.
type PostEmbeddingsImagesMultipartRequestBody PostEmbeddingsImagesMultipartBody

// PostEmbeddingsMultimodalMultipartRequestBody defines body for PostEmbeddingsMultimodal for multipart/form-data ContentType.
type PostEmbeddingsMultimodalMultipartRequestBody PostEmbeddingsMultimodalMultipartBody

// PostEmbeddingsTextJSONRequestBody defines body for PostEmbeddingsText for application/json ContentType.
type PostEmbeddingsTextJSONRequestBody PostEmbeddingsTextJSONBody
