// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 次の pending ジョブをロックして取得
	// (POST /internal/worker/jobs/claim)
	ClaimWorkerJob(ctx *echo.Context) error
	// ジョブを完了にする
	// (POST /internal/worker/jobs/{id}/complete)
	CompleteWorkerJob(ctx *echo.Context, id JobId) error
	// ジョブを失敗にする
	// (POST /internal/worker/jobs/{id}/fail)
	FailWorkerJob(ctx *echo.Context, id JobId) error
	// 画像群の埋め込みジョブを受け付ける
	// (POST /v1/embeddings/images)
	PostEmbeddingsImages(ctx *echo.Context) error
	// 埋め込みジョブの状態と結果を取得する
	// (GET /v1/embeddings/jobs/{id})
	GetEmbeddingsJob(ctx *echo.Context, id JobId) error
	// テキストと画像群の埋め込みジョブを受け付ける
	// (POST /v1/embeddings/multimodal)
	PostEmbeddingsMultimodal(ctx *echo.Context) error
	// テキストの埋め込みベクトルを返す
	// (POST /v1/embeddings/text)
	PostEmbeddingsText(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ClaimWorkerJob converts echo context to params.
func (w *ServerInterfaceWrapper) ClaimWorkerJob(ctx *echo.Context) error {
	var err error

	ctx.Set(string(InternalBearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ClaimWorkerJob(ctx)
	return err
}

// CompleteWorkerJob converts echo context to params.
func (w *ServerInterfaceWrapper) CompleteWorkerJob(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(InternalBearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CompleteWorkerJob(ctx, id)
	return err
}

// FailWorkerJob converts echo context to params.
func (w *ServerInterfaceWrapper) FailWorkerJob(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(InternalBearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FailWorkerJob(ctx, id)
	return err
}

// PostEmbeddingsImages converts echo context to params.
func (w *ServerInterfaceWrapper) PostEmbeddingsImages(ctx *echo.Context) error {
	var err error

	ctx.Set(string(ExternalBearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEmbeddingsImages(ctx)
	return err
}

// GetEmbeddingsJob converts echo context to params.
func (w *ServerInterfaceWrapper) GetEmbeddingsJob(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(ExternalBearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEmbeddingsJob(ctx, id)
	return err
}

// PostEmbeddingsMultimodal converts echo context to params.
func (w *ServerInterfaceWrapper) PostEmbeddingsMultimodal(ctx *echo.Context) error {
	var err error

	ctx.Set(string(ExternalBearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEmbeddingsMultimodal(ctx)
	return err
}

// PostEmbeddingsText converts echo context to params.
func (w *ServerInterfaceWrapper) PostEmbeddingsText(ctx *echo.Context) error {
	var err error

	ctx.Set(string(ExternalBearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEmbeddingsText(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/internal/worker/jobs/claim", wrapper.ClaimWorkerJob, options.OperationMiddlewares["claimWorkerJob"]...)
	router.POST(options.BaseURL+"/internal/worker/jobs/:id/complete", wrapper.CompleteWorkerJob, options.OperationMiddlewares["completeWorkerJob"]...)
	router.POST(options.BaseURL+"/internal/worker/jobs/:id/fail", wrapper.FailWorkerJob, options.OperationMiddlewares["failWorkerJob"]...)
	router.POST(options.BaseURL+"/v1/embeddings/images", wrapper.PostEmbeddingsImages, options.OperationMiddlewares["postEmbeddingsImages"]...)
	router.GET(options.BaseURL+"/v1/embeddings/jobs/:id", wrapper.GetEmbeddingsJob, options.OperationMiddlewares["getEmbeddingsJob"]...)
	router.POST(options.BaseURL+"/v1/embeddings/multimodal", wrapper.PostEmbeddingsMultimodal, options.OperationMiddlewares["postEmbeddingsMultimodal"]...)
	router.POST(options.BaseURL+"/v1/embeddings/text", wrapper.PostEmbeddingsText, options.OperationMiddlewares["postEmbeddingsText"]...)

}

type NoContentResponse struct {
}

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate *string
}
type UnauthorizedJSONResponse struct {
	Body ErrorResponse

	Headers UnauthorizedResponseHeaders
}

type ClaimWorkerJobRequestObject struct {
	Body *ClaimWorkerJobJSONRequestBody
}

type ClaimWorkerJobResponseObject interface {
	VisitClaimWorkerJobResponse(w http.ResponseWriter) error
}

type ClaimWorkerJob200JSONResponse struct {
	Id JobId `json:"id"`

	// Payload worker が処理するジョブ内容
	Payload WorkerJobPayload `json:"payload"`
}

func (response ClaimWorkerJob200JSONResponse) VisitClaimWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimWorkerJob204Response = NoContentResponse

func (response ClaimWorkerJob204Response) VisitClaimWorkerJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ClaimWorkerJob400JSONResponse ErrorResponse

func (response ClaimWorkerJob400JSONResponse) VisitClaimWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimWorkerJob401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ClaimWorkerJob401JSONResponse) VisitClaimWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimWorkerJob500JSONResponse ErrorResponse

func (response ClaimWorkerJob500JSONResponse) VisitClaimWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteWorkerJobRequestObject struct {
	Id   JobId `json:"id"`
	Body *CompleteWorkerJobJSONRequestBody
}

type CompleteWorkerJobResponseObject interface {
	VisitCompleteWorkerJobResponse(w http.ResponseWriter) error
}

type CompleteWorkerJob204Response = NoContentResponse

func (response CompleteWorkerJob204Response) VisitCompleteWorkerJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CompleteWorkerJob400JSONResponse ErrorResponse

func (response CompleteWorkerJob400JSONResponse) VisitCompleteWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteWorkerJob401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CompleteWorkerJob401JSONResponse) VisitCompleteWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteWorkerJob404JSONResponse ErrorResponse

func (response CompleteWorkerJob404JSONResponse) VisitCompleteWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteWorkerJob500JSONResponse ErrorResponse

func (response CompleteWorkerJob500JSONResponse) VisitCompleteWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type FailWorkerJobRequestObject struct {
	Id JobId `json:"id"`
}

type FailWorkerJobResponseObject interface {
	VisitFailWorkerJobResponse(w http.ResponseWriter) error
}

type FailWorkerJob204Response = NoContentResponse

func (response FailWorkerJob204Response) VisitFailWorkerJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type FailWorkerJob400JSONResponse ErrorResponse

func (response FailWorkerJob400JSONResponse) VisitFailWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type FailWorkerJob401JSONResponse struct{ UnauthorizedJSONResponse }

func (response FailWorkerJob401JSONResponse) VisitFailWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type FailWorkerJob404JSONResponse ErrorResponse

func (response FailWorkerJob404JSONResponse) VisitFailWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type FailWorkerJob500JSONResponse ErrorResponse

func (response FailWorkerJob500JSONResponse) VisitFailWorkerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImagesRequestObject struct {
	Body *multipart.Reader
}

type PostEmbeddingsImagesResponseObject interface {
	VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error
}

type PostEmbeddingsImages202JSONResponse EmbeddingJobAccepted

func (response PostEmbeddingsImages202JSONResponse) VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImages400JSONResponse ErrorResponse

func (response PostEmbeddingsImages400JSONResponse) VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImages401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostEmbeddingsImages401JSONResponse) VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsImages500JSONResponse ErrorResponse

func (response PostEmbeddingsImages500JSONResponse) VisitPostEmbeddingsImagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetEmbeddingsJobRequestObject struct {
	Id JobId `json:"id"`
}

type GetEmbeddingsJobResponseObject interface {
	VisitGetEmbeddingsJobResponse(w http.ResponseWriter) error
}

type GetEmbeddingsJob200JSONResponse EmbeddingJobStatus

func (response GetEmbeddingsJob200JSONResponse) VisitGetEmbeddingsJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEmbeddingsJob401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetEmbeddingsJob401JSONResponse) VisitGetEmbeddingsJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetEmbeddingsJob404JSONResponse ErrorResponse

func (response GetEmbeddingsJob404JSONResponse) VisitGetEmbeddingsJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetEmbeddingsJob500JSONResponse ErrorResponse

func (response GetEmbeddingsJob500JSONResponse) VisitGetEmbeddingsJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsMultimodalRequestObject struct {
	Body *multipart.Reader
}

type PostEmbeddingsMultimodalResponseObject interface {
	VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error
}

type PostEmbeddingsMultimodal202JSONResponse EmbeddingJobAccepted

func (response PostEmbeddingsMultimodal202JSONResponse) VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsMultimodal400JSONResponse ErrorResponse

func (response PostEmbeddingsMultimodal400JSONResponse) VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsMultimodal401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostEmbeddingsMultimodal401JSONResponse) VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsMultimodal500JSONResponse ErrorResponse

func (response PostEmbeddingsMultimodal500JSONResponse) VisitPostEmbeddingsMultimodalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsTextRequestObject struct {
	Body *PostEmbeddingsTextJSONRequestBody
}

type PostEmbeddingsTextResponseObject interface {
	VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error
}

type PostEmbeddingsText200JSONResponse EmbeddingResult

func (response PostEmbeddingsText200JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText400JSONResponse ErrorResponse

func (response PostEmbeddingsText400JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostEmbeddingsText401JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText500JSONResponse ErrorResponse

func (response PostEmbeddingsText500JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText503ResponseHeaders struct {
	RetryAfter int
}

type PostEmbeddingsText503JSONResponse struct {
	Body    ErrorResponse
	Headers PostEmbeddingsText503ResponseHeaders
}

func (response PostEmbeddingsText503JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PostEmbeddingsText504JSONResponse ErrorResponse

func (response PostEmbeddingsText504JSONResponse) VisitPostEmbeddingsTextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(504)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// 次の pending ジョブをロックして取得
	// (POST /internal/worker/jobs/claim)
	ClaimWorkerJob(ctx context.Context, request ClaimWorkerJobRequestObject) (ClaimWorkerJobResponseObject, error)
	// ジョブを完了にする
	// (POST /internal/worker/jobs/{id}/complete)
	CompleteWorkerJob(ctx context.Context, request CompleteWorkerJobRequestObject) (CompleteWorkerJobResponseObject, error)
	// ジョブを失敗にする
	// (POST /internal/worker/jobs/{id}/fail)
	FailWorkerJob(ctx context.Context, request FailWorkerJobRequestObject) (FailWorkerJobResponseObject, error)
	// 画像群の埋め込みジョブを受け付ける
	// (POST /v1/embeddings/images)
	PostEmbeddingsImages(ctx context.Context, request PostEmbeddingsImagesRequestObject) (PostEmbeddingsImagesResponseObject, error)
	// 埋め込みジョブの状態と結果を取得する
	// (GET /v1/embeddings/jobs/{id})
	GetEmbeddingsJob(ctx context.Context, request GetEmbeddingsJobRequestObject) (GetEmbeddingsJobResponseObject, error)
	// テキストと画像群の埋め込みジョブを受け付ける
	// (POST /v1/embeddings/multimodal)
	PostEmbeddingsMultimodal(ctx context.Context, request PostEmbeddingsMultimodalRequestObject) (PostEmbeddingsMultimodalResponseObject, error)
	// テキストの埋め込みベクトルを返す
	// (POST /v1/embeddings/text)
	PostEmbeddingsText(ctx context.Context, request PostEmbeddingsTextRequestObject) (PostEmbeddingsTextResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ClaimWorkerJob operation middleware
func (sh *strictHandler) ClaimWorkerJob(ctx *echo.Context) error {
	var request ClaimWorkerJobRequestObject

	var body ClaimWorkerJobJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimWorkerJob(ctx.Request().Context(), request.(ClaimWorkerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimWorkerJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ClaimWorkerJobResponseObject); ok {
		return validResponse.VisitClaimWorkerJobResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CompleteWorkerJob operation middleware
func (sh *strictHandler) CompleteWorkerJob(ctx *echo.Context, id JobId) error {
	var request CompleteWorkerJobRequestObject

	request.Id = id

	var body CompleteWorkerJobJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteWorkerJob(ctx.Request().Context(), request.(CompleteWorkerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteWorkerJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CompleteWorkerJobResponseObject); ok {
		return validResponse.VisitCompleteWorkerJobResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// FailWorkerJob operation middleware
func (sh *strictHandler) FailWorkerJob(ctx *echo.Context, id JobId) error {
	var request FailWorkerJobRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FailWorkerJob(ctx.Request().Context(), request.(FailWorkerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FailWorkerJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(FailWorkerJobResponseObject); ok {
		return validResponse.VisitFailWorkerJobResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostEmbeddingsImages operation middleware
func (sh *strictHandler) PostEmbeddingsImages(ctx *echo.Context) error {
	var request PostEmbeddingsImagesRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostEmbeddingsImages(ctx.Request().Context(), request.(PostEmbeddingsImagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEmbeddingsImages")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostEmbeddingsImagesResponseObject); ok {
		return validResponse.VisitPostEmbeddingsImagesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEmbeddingsJob operation middleware
func (sh *strictHandler) GetEmbeddingsJob(ctx *echo.Context, id JobId) error {
	var request GetEmbeddingsJobRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetEmbeddingsJob(ctx.Request().Context(), request.(GetEmbeddingsJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEmbeddingsJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetEmbeddingsJobResponseObject); ok {
		return validResponse.VisitGetEmbeddingsJobResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostEmbeddingsMultimodal operation middleware
func (sh *strictHandler) PostEmbeddingsMultimodal(ctx *echo.Context) error {
	var request PostEmbeddingsMultimodalRequestObject

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostEmbeddingsMultimodal(ctx.Request().Context(), request.(PostEmbeddingsMultimodalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEmbeddingsMultimodal")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostEmbeddingsMultimodalResponseObject); ok {
		return validResponse.VisitPostEmbeddingsMultimodalResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostEmbeddingsText operation middleware
func (sh *strictHandler) PostEmbeddingsText(ctx *echo.Context) error {
	var request PostEmbeddingsTextRequestObject

	var body PostEmbeddingsTextJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostEmbeddingsText(ctx.Request().Context(), request.(PostEmbeddingsTextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEmbeddingsText")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostEmbeddingsTextResponseObject); ok {
		return validResponse.VisitPostEmbeddingsTextResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FpfVxNJFv8qfXr3bYIJyOw6eYMZxoPjqIu4nj0ux+kkBbQm3Znujspyck6qGzBAWBjkz+AwIooQQRJ3",
	"d2YWTYQPU3QCT3yFPVXVf9OdgIDM7qwv2nS6qu69de/vd++tGmSjYiIpCkBQZDY8yCY5iUsABUjkr0ti",
	"pDOGH3iBDbNJTulnA6zAJQAbZvkYG2Al8G2Kl0CMDStSCgRYOdoPEhwe8XsJ9LJh9ndBe/4g/VUO0mnT",
	"6TSeQE6KggzIclfEz0VBAYKC/4gBOSrxSYUX8dpXRMb8LR1gbwhcSukXJf5vgIgXtYdxyWScj3J4WPCO",
	"jMcOHlGqDkkSpS5DHiqdW4a2a53MXTDA8DKT4GWZF/oYUWJ44R4XJ8boB1zMMNzNmzeb2lJKPxAULAzw",
	"KtQOOAlIDGd/xIsCE+3n4nEg9AHWaUtlIIktLisSL/RhybBshtj498/jHJ+4KUp3gXRJjHSBb1NAJsZI",
	"SmISSApPzXuXF2KyVxJ9ck7fnkdwHsElBIeQuoW0NaTNVfMFPfsCZdTqIqzOvqgsqAgWGQU8UBgE8wyf",
	"4PrAQTlLX6jT+tC6Ppwl06zu7cwguHBQHkUZ9a8CG2B5BSTkwzbA0uArXojhbTb05iSJG2DT9gsxcgdE",
	"iSN0JCIgFuOFvk4szZd83MfS+tI4UuHedhnBHQQ3qjN5ouV4daaka5NIm0LqCtLGkLZOpNWL2/rOov7u",
	"mV6eDFMtg0mhL2A83kkC6/k+iCTJmGakzSJ1mUy0gaCKLamOVRYz+soa0xJivubbD8rZltBnf2z+tCXE",
	"RAYUIDus0ytKCU5hw2yEFzhpgA2wCe7BZSD0Kf1s2BwVqHWDWu2vUqt49L9PzMogmNMn1erwGoILtvbq",
	"OtLm8Jara0gtIi3LBmq9Bgw0mtM7A1Lf4H+1V0gr4/dwHKmjppM1Whqpm0grsx5F006cuUUE6jnUF6g1",
	"5JOaA8ECdgyi0lH92Hdb0gE2wQuddHxzrW87pL8kRtqiUZBUKLS5N4OPHRVb3TbjY41NdkmMXFc4JSWf",
	"YEkC5qm4cmTzdNHPMZZZawMhlcACJ4GAP6HeGAUEbdkAIas4wKYJsL0cHwdOver4C8FmY4WGRuiyxHdb",
	"4B6IKqLk9aTK5vO91Uk9N1fZyhJsKbigRlswXEjbIIH+p/tAON/058tN1oJNF9oZPOrhW33sh8qrZX1Y",
	"wxDbGvrsDx7gtDCiNy5yih0kQioRARJxL+6B4V54Aqe70b89aOo0kqFjQ/t0gwfK0eEVaSM4oCkYUJDM",
	"LF5o/qyFqcw91DfnMbG8fGs8w+Lu1oQ+WTTVduAfHkKUMV80+yGhi7s9O5gAssz1+XADUvNIe4mBSltG",
	"mobUEgWtQ0HInNHPYFbWZO1ZKkWc0CP2TRDpF8W7N6S4n2gGD+uF3O7bEaSV9JV/VGbnCQ9vMNeuXu9m",
	"KHYxN7ouH5Szu6VSZWjyoDzqZJSUxNfSSesFP0lc3OsRxmD9ogGTcB3zvCkgykDCh/YHu6XvEZywPjgo",
	"ZxOpuMInxBgXZ/SpDaRmqJxmuOP5sbcn3Db1ke8aNxAXuVhDXH+4Wp0aobaxrTgyrBfeeNiNrHhbtMni",
	"fYFdJomKERlHGkzCyCebwTgIoimJVwau4zFUwI4HCpAELk7zRZxTWhktHhwhr23f6leUJJaoUzjGMCwC",
	"L/SKPs6oPcEwpkGkPSPRkkHahjPySdgX7NyxsFydGmHarnWSiHZhASzqU7nK4hLKQDMFKzncA8Hi/o9P",
	"6CckaWphPmHuiBGGjzFB5j6NGCbIXOzoNlMofSq3u5VxL+LC4urPU5UniwgWkfozEX8KaWV9ZHhfyyO4",
	"RvKO5yT8/420FwjOIjWHfYfMPfxqf24ca4Ilw//f/qrjLygDg7xhYvK+80p3R9eVtsu3jQ9wRswYOb4i",
	"3gUCzplpcryfgebkeAN4BSetLLBIQQbSPSDhldgAew9IMt2C0LnmcyG8tWISCFySZ8Ps+XOhc+exS3NK",
	"P3EWS6YgjYbgHTEiB6O4PCCgKMo+AP5FO6OPDCNYYAzSZezIVqebd0u/MDYHMwhuYDUykI+RMiBJ4xHr",
	"S7N+otg3pNb4hkFwraa8MKoKdbqSe6gXHmPzY6QYb1xnYJrc3VquzL0xKw5abpge4ItPdWCpDhqRefZe",
	"/lN/98jWH+aqQ8sIDulPf9KnsOsyLaFWc+swjpCyDaN9TRFm1MZAVtrF2MCp1aj+lV7aW0q3hELvteix",
	"c76kjcdHqu1M/PbN0szJvKzqrcYdm6QidQzL0hJqrSeHZZyg3WRIB9jW9zTTifoHJCawJ5uun9vdmqhs",
	"PicxsEDFaT5cAVfzIx1gPz1LHXwA1EyhXAzGhm8N+pLQrZ50T4CVU4kErnTDbOXVcj3oQdomAeUixU0K",
	"JBgyuT6ZuIwxfRMFO7YHC+APgYN8LB00iwcnFNbEsPGFM4ydHbFb/tazPzHjouf44e+OxGOWVDXBZcxy",
	"lLCy06i9fLZaMIDbh0xdeO/kXldBYAdpwcBQzH62D2FOho8QLFiz0v6Lmb1tkm+8FL21u/Ojvvm98ZkB",
	"yO5upBcS/6vRgbQZijiajAzmdNChlWp9NjqYwEa43kGie6vjCK6QTtAYgtsI/oDUR//72OUEK6NKw9kR",
	"dskTwFQvx8frQ9SXHB8/HXj6GBofQ+NsQoP0LY4eGveag1Y1JAdJDi/XL1+cKzFftOMCZffdYiU7RbMG",
	"vCacMgtIi7UOyllHlWmUkSSE9e0czvONQvN2SoqTNjdOMnMIvt7PPK4uvaDlxcWObqZGWiuMGcJaqln9",
	"2FWOT+lwTZQVi8LlTqpwowyC1C9JTlKCvaKUaIpxCtcwnbdMeIz+NTlUcbcXD2llO0x3aFlgN8A8BQEV",
	"2j9nOYzpW04vdPz68g3LEXVan5xH8DtSbX6H4NKZ46XlHgxBlCXsz9ScDDmoek5ifQNpozVQelDOVp48",
	"rsy+RloJQ4K6gtS3SCvR0zCsmdW7+21UKxZe0QZBdXultotfb1tdOGYDgC+EWaCAFeoDPqx+ETgA4FSJ",
	"PfRBIsE4LGoUB9WxXyrD4x/J+Sy9uF7pRfcCwbxdZTnOY4/uyHbfrD4fk1bcJybeVGfyKKOap6sGfljd",
	"tHqN3pq2XsE4XaPDVJVWjAwQYkmRFxRCtY7JrEzjoJw13+T0neG9VYjgOlJHa0nbvMKw+24HwRHHwXwj",
	"mv7atsWJqJoTBq72khB3sh85UehJBwZ9ORHH+a9K8cc48DhJXvAxA3hPyMD7g7SSSfp1Wo7/v3TvPivK",
	"f1D2N2PlGOVLBtKzTLO5sI3gmr49XHm5ZBY35G5NvVsHrhad3yHZ+5yHZWDte20aP2tZemKjT/yrsqDu",
	"7czoEz8dBT+76ZHv6bRJj3cA6wXcY0HNB0ixrD6ux8frbfav0JRxelKuOrSsj73BXmKVHJeuX73C/PZO",
	"ObAs589SlnoYNEo6EkZWijIqwYTX+D2c1LeHEXxuQ8TIxD7eGgoakwg+xVENh9y3VruAIg00tfUqwO+2",
	"09/z+os80taJv71E6gpFouradGX2dcO7wEZM8YIC+oBkHFd+epYJvn0NxLgbkkPqDrmu+RSpz5C6Spx4",
	"nlhznhB2A7ooHAq4dcmhtpXmd7vDaKWRWwC09nPrsj83Xl14W51+rT/T2ABLsilygSMcDMbFKBfvF2Ul",
	"fCF0IUTqQUOQQe9lZnpPAa7trU/s5cuUb1yaaiXrgobz/UHZvC7ppR+Hs5o0ZpQYxrVxhz1wdusWynuL",
	"wpaOHPRoRXI/awNp5epM3nEZvaaRmO5J/ycAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
