[tools]
python = "3.12"
go = "1.26.2"
uv = "0.11"
oapi-codegen = "2.7.0"

[tasks.oapi-gen]
description = "openapiからのコード生成"
dir = "server"
run = [
    "oapi-codegen -config ./api/oapi.model.config.yaml ../openapi.yaml",
    "oapi-codegen -config ./api/oapi.interface.config.yaml ../openapi.yaml",
]

[tasks.up]
description = "docker compose up --build"
run = "docker compose up --build"

[tasks.down]
description = "docker compose down"
run = "docker compose down"

[tasks.dev-up]
description = "開発環境のコンテナを立ち上げる"
run = "docker compose -f development/compose.yaml up --build"

[tasks.dev-down]
description = "開発環境のコンテナを削除する"
run = "docker compose -f development/compose.yaml down"
